
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: May 19 2026 13:53:48 IST (May 19 2026 08:23:48 UTC)

// Verification Directory fv/dadda_multiplier_4x4 

module dadda_multiplier_4x4(A, B, P);
  input [3:0] A, B;
  output [7:0] P;
  wire [3:0] A, B;
  wire [7:0] P;
  wire n_0, n_1, n_2, n_3, n_4, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_30, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_51, n_52, n_54;
  wire n_70;
  CLKXOR2X2 g1034__2398(.A (n_27), .B (n_54), .Y (P[6]));
  CLKXOR2X2 g1035__5107(.A (n_44), .B (n_51), .Y (P[5]));
  AO21X2 g1036__6260(.A0 (n_25), .A1 (n_48), .B0 (n_26), .Y (P[7]));
  OAI21XL g1037__4319(.A0 (n_52), .A1 (n_45), .B0 (n_49), .Y (n_54));
  CLKXOR2X2 g1038__8428(.A (n_52), .B (n_42), .Y (P[4]));
  OAI21XL g1039__5526(.A0 (n_52), .A1 (n_41), .B0 (n_46), .Y (n_51));
  CLKXOR2X2 g1043__6783(.A (n_40), .B (n_47), .Y (P[3]));
  INVXL g1040(.A (n_48), .Y (n_49));
  AOI2BB1XL g1049__3680(.A0N (n_47), .A1N (n_39), .B0 (n_38), .Y
       (n_52));
  AOI21XL g1041__1617(.A0 (n_43), .A1 (n_46), .B0 (n_45), .Y (n_48));
  NOR2BXL g1042__2802(.AN (n_43), .B (n_45), .Y (n_44));
  NAND2BXL g1044__1705(.AN (n_41), .B (n_46), .Y (n_42));
  OR2X1 g1051__5122(.A (n_39), .B (n_38), .Y (n_40));
  NOR2BXL g1054__8246(.AN (n_36), .B (n_37), .Y (n_39));
  NOR2BXL g1047__7098(.AN (n_35), .B (n_34), .Y (n_41));
  NOR2BXL g1055__6131(.AN (n_37), .B (n_36), .Y (n_38));
  NAND2XL g1045__1881(.A (n_33), .B (n_32), .Y (n_43));
  NAND2BXL g1048__5115(.AN (n_35), .B (n_34), .Y (n_46));
  NOR2XL g1046__7482(.A (n_33), .B (n_32), .Y (n_45));
  CLKXOR2X2 g1052__4733(.A (n_70), .B (n_30), .Y (P[2]));
  ADDFX1 g1050__6161(.A (n_11), .B (n_4), .CI (n_16), .CO (n_32), .S
       (n_34));
  ADDFX1 g1056__9315(.A (n_0), .B (n_1), .CI (n_17), .CO (n_35), .S
       (n_36));
  AOI21XL g1058__9945(.A0 (n_19), .A1 (n_18), .B0 (n_28), .Y (n_30));
  OAI21XL g1059__2883(.A0 (n_21), .A1 (n_22), .B0 (n_23), .Y (n_33));
  NOR2XL g1053__2346(.A (n_70), .B (n_28), .Y (n_47));
  NOR2XL g1057__1666(.A (n_26), .B (n_24), .Y (n_27));
  INVXL g1061(.A (n_24), .Y (n_25));
  NAND2XL g1060__7410(.A (n_22), .B (n_21), .Y (n_23));
  AOI21X4 g1064__6417(.A0 (n_2), .A1 (n_3), .B0 (n_70), .Y (P[1]));
  NOR2XL g1062__5477(.A (n_19), .B (n_18), .Y (n_28));
  AOI21XL g1063__2398(.A0 (B[3]), .A1 (A[3]), .B0 (n_22), .Y (n_24));
  XNOR2X1 g1068__5107(.A (n_10), .B (n_9), .Y (n_17));
  CLKXOR2X1 g1067__4319(.A (n_13), .B (n_12), .Y (n_16));
  XNOR2X1 g1066__8428(.A (n_8), .B (n_7), .Y (n_18));
  XNOR2X1 g1065__5526(.A (n_15), .B (n_14), .Y (n_21));
  NOR2XL g1069__6783(.A (n_15), .B (n_14), .Y (n_26));
  NOR2XL g1072__3680(.A (n_13), .B (n_12), .Y (n_22));
  NOR2XL g1073__1617(.A (n_10), .B (n_9), .Y (n_11));
  NOR2XL g1071__2802(.A (n_8), .B (n_7), .Y (n_37));
  AND2X1 g1089__1705(.A (B[3]), .B (A[1]), .Y (n_4));
  NAND2XL g1074__5122(.A (B[1]), .B (A[0]), .Y (n_3));
  NAND2XL g1077__8246(.A (B[3]), .B (A[2]), .Y (n_15));
  NAND2XL g1075__7098(.A (B[2]), .B (A[0]), .Y (n_8));
  NAND2XL g1085__6131(.A (B[2]), .B (A[3]), .Y (n_14));
  NAND2XL g1076__1881(.A (B[1]), .B (A[3]), .Y (n_12));
  NAND2XL g1078__5115(.A (B[1]), .B (A[1]), .Y (n_19));
  NAND2XL g1082__7482(.A (B[0]), .B (A[1]), .Y (n_2));
  NAND2XL g1080__4733(.A (B[3]), .B (A[0]), .Y (n_1));
  NAND2XL g1088__6161(.A (B[2]), .B (A[1]), .Y (n_0));
  NAND2XL g1084__9315(.A (B[0]), .B (A[3]), .Y (n_9));
  NAND2XL g1086__9945(.A (B[2]), .B (A[2]), .Y (n_13));
  NAND2XL g1079__2883(.A (B[1]), .B (A[2]), .Y (n_10));
  AND2X2 g1083__2346(.A (B[0]), .B (A[0]), .Y (P[0]));
  NAND2XL g1087__1666(.A (B[0]), .B (A[2]), .Y (n_7));
  NOR2BX1 g2(.AN (P[0]), .B (n_19), .Y (n_70));
endmodule

